import type {
  AuctionBid,
  Block,
  CmsEntry,
  DashboardData,
  Payment,
  Registration,
  VolunteerSubmission,
} from "./types";

export const seedBlocks: Block[] = [
  "Block A",
  "Block B",
  "Block C",
  "Block D",
  "Block E",
  "Block F",
  "Block G",
].map((name) => {
  const suffix = name.toLowerCase().replace(" ", "");
  return {
    id: suffix,
    name,
    organizerName: `${name} Organizer`,
    organizerPhone: "9876543210",
    upiId: `avani.${suffix}@axl`,
    qrImageUrl: "",
    paymentProvider: "upi_qr",
    razorpayKeyId: "",
    razorpayLink: "",
    isActive: true,
  };
});

export const seedCmsEntries: CmsEntry[] = [
  {
    id: "event-cultural-evening",
    section: "event",
    title: "Grand Cultural Evening",
    subtitle: "19 Sept 2026 | 7:00 PM onwards",
    body: "Music, dance, skits and cultural performances by Avani family members.",
    imageUrl: "/uploads/cultural-evening.jpg",
    label: "Event",
    color: "#8E1119",
    startsAt: "2026-09-19T19:00",
    venue: "Community Hall",
    sortOrder: 10,
    isPublished: true,
  },
  {
    id: "event-kids-activities",
    section: "event",
    title: "Kids Activity and Competitions",
    subtitle: "6 - 19 Sept 2026",
    body: "Creative games, stage activities and competitions for young residents.",
    imageUrl: "",
    label: "Event",
    color: "#E7A32B",
    startsAt: "2026-09-06T10:00",
    venue: "Club House",
    sortOrder: 20,
    isPublished: true,
  },
  {
    id: "schedule-ganesh-pooja",
    section: "schedule",
    title: "Ganesh Pooja",
    subtitle: "",
    body: "Daily morning pooja.",
    imageUrl: "",
    label: "07:00 AM",
    color: "#E7A32B",
    startsAt: "",
    venue: "Mandap",
    sortOrder: 10,
    isPublished: true,
  },
  {
    id: "schedule-cultural-program",
    section: "schedule",
    title: "Cultural Program",
    subtitle: "Main Stage",
    body: "Evening performances.",
    imageUrl: "",
    label: "07:30 PM",
    color: "#0D7B8B",
    startsAt: "",
    venue: "Main Stage",
    sortOrder: 20,
    isPublished: true,
  },
  {
    id: "announcement-water-maintenance",
    section: "announcement",
    title: "Water Supply Maintenance",
    subtitle: "20 May 2026 - 10:30 AM",
    body: "Water supply will be unavailable in Blocks G, H and I on 25 May 2026 from 9:00 AM to 1:00 PM.",
    imageUrl: "",
    label: "Important",
    color: "#1E8CD8",
    startsAt: "",
    venue: "",
    sortOrder: 10,
    isPublished: true,
  },
  {
    id: "gallery-ganesh-alankaram",
    section: "gallery",
    title: "Ganesh Alankaram",
    subtitle: "Main mandap",
    body: "",
    imageUrl: "/uploads/gallery-1.jpg",
    label: "Photo",
    color: "#8E1119",
    startsAt: "",
    venue: "",
    sortOrder: 10,
    isPublished: true,
  },
  {
    id: "role-pooja",
    section: "volunteer_role",
    title: "Pooja and Rituals",
    subtitle: "",
    body: "Help coordinate daily pooja flow.",
    imageUrl: "",
    label: "Volunteer",
    color: "#8E1119",
    startsAt: "",
    venue: "",
    sortOrder: 10,
    isPublished: true,
  },
  {
    id: "role-collection-support",
    section: "volunteer_role",
    title: "Collection Support",
    subtitle: "",
    body: "Assist block collection kiosks and reconciliation.",
    imageUrl: "",
    label: "Volunteer",
    color: "#E7A32B",
    startsAt: "",
    venue: "",
    sortOrder: 20,
    isPublished: true,
  },
  {
    id: "setting-theme",
    section: "app_setting",
    title: "Festival theme",
    subtitle: "Avani Ganesh Utsav 2026",
    body: "Primary palette, greeting copy and mobile home hero messaging.",
    imageUrl: "",
    label: "Theme",
    color: "#8E1119",
    startsAt: "",
    venue: "",
    sortOrder: 10,
    isPublished: true,
  },
];

export const seedPayments: Payment[] = [
  {
    id: "pay-1001",
    amount: 5001,
    blockId: "blocka",
    blockName: "Block A",
    residentName: "Ramesh Kumar",
    email: "ramesh.kumar@email.com",
    phone: "9876543210",
    flatNumber: "A-1203",
    gotram: "Kashyap",
    provider: "upi_qr",
    status: "paid",
    referenceId: "UPI-AVANI-1001",
    createdAt: "2026-08-31T10:30:00.000Z",
    paidAt: "2026-08-31T10:34:00.000Z",
  },
  {
    id: "pay-1002",
    amount: 2001,
    blockId: "blockb",
    blockName: "Block B",
    residentName: "Neha Rao",
    email: "neha.rao@email.com",
    phone: "9898989898",
    flatNumber: "B-804",
    gotram: "",
    provider: "upi_qr",
    status: "pending",
    referenceId: "",
    createdAt: "2026-08-31T11:15:00.000Z",
    paidAt: "",
  },
];

export const seedRegistrations: Registration[] = [
  {
    id: "reg-1001",
    eventTitle: "Grand Cultural Evening",
    participantName: "Arjun Rao",
    flatNumber: "I-1204",
    ageGroup: "11 - 15 years",
    mobile: "9876543210",
    status: "confirmed",
    createdAt: "2026-08-30T16:10:00.000Z",
  },
];

export const seedVolunteers: VolunteerSubmission[] = [
  {
    id: "vol-1001",
    name: "Priya Shah",
    flatNumber: "C-506",
    mobile: "9123456780",
    roles: ["Decoration", "Photography"],
    note: "Available weekends",
    createdAt: "2026-08-29T12:20:00.000Z",
  },
];

export const seedBids: AuctionBid[] = [
  {
    id: "bid-1001",
    itemTitle: "Laddoo Auction",
    amount: 12001,
    bidderName: "Amit Jain",
    flatNumber: "I-1302",
    mobile: "9000011111",
    status: "leading",
    createdAt: "2026-08-31T13:05:00.000Z",
  },
];

export function createSeedDashboardData(): DashboardData {
  const paid = seedPayments.filter((payment) => payment.status === "paid");
  const pending = seedPayments.filter((payment) => payment.status === "pending");

  return {
    blocks: seedBlocks,
    payments: seedPayments,
    cmsEntries: seedCmsEntries,
    registrations: seedRegistrations,
    volunteers: seedVolunteers,
    bids: seedBids,
    totals: {
      collected: paid.reduce((sum, payment) => sum + payment.amount, 0),
      pending: pending.reduce((sum, payment) => sum + payment.amount, 0),
      registrations: seedRegistrations.length,
      volunteers: seedVolunteers.length,
    },
  };
}
